const mongoose = require('mongoose');

const TranscriptionSchema = new mongoose.Schema({
  audioUrl: {
    type: String,
    required: true // Stores the file path or URL of the uploaded audio
  },
  transcriptionText: {
    type: String,
    required: true // Stores the text generated by the Speech-to-Text API
  },
  createdAt: {
    type: Date,
    default: Date.now // Automatically tracks when the file was processed
  }
});

module.exports = mongoose.model('Transcription', TranscriptionSchema);
